APP-Campus-Online-v6.0/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views
from .views import (DashboardView, _PasswordChangeView, _PasswordChangeDoneView, _PasswordResetView,
    _PasswordResetDoneView, _PasswordResetConfirmView, _PasswordResetCompleteView,
    CreateUser, UserCreated, UsersView, UpdateUser, UsersView)


urlpatterns = [
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('sair/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('painel/', DashboardView.as_view(), name='dashboard'),
    path('alterar-senha/', _PasswordChangeView.as_view(), name='edit_password'),
    path('alterar-senha/senha-alterada-com-sucesso', _PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('nova-senha/', _PasswordResetView.as_view(), name='password_reset'),
    path('nova-senha/nova-senha-solicitada', _PasswordResetDoneView.as_view()),
    path('confirmar-nova-senha/<uidb64>/<token>', _PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirmar-nova-senha/<uidb64>/senha-redefinida-com-sucesso', _PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('novo-usuario/', CreateUser.as_view(), name='new_user'),
    path('novo-usuario/usuario-inserido-com-sucesso', UserCreated.as_view()),
    path('atualizar-usuario/<int:pk>/', UpdateUser, name='update_user'),
    path('usuarios/', UsersView.as_view(), name='users'),
 ]

APP-Campus-Online-v6.0/campus_app/urls.py
from django.urls import path
from .views import HomeView, NoticiaCreate, NoticiaCreateLongForm, NoticiaUpdateLongForm, VideoCreateLongForm, VideoUpdateLongForm, ImagemCreateLongForm, ImagemUpdateLongForm, TextoCreateLongForm, TextoUpdateLongForm, ShowNoticiaLongForm, NoticiaView, NoticiaUpdate, NoticiaDelete, NoticiaDataView
from .views import WhatsAppAccountView, WhatsAppAccountCreate, WhatsAppAccountUpdate, WhatsAppAccountDelete

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('noticia_archive_day/<int:year>/<int:month>/<int:day>', NoticiaDataView.as_view(month_format='%m'),
         name='noticia_data'),
    path('noticia_list/', NoticiaView.as_view(), name='noticia_list'),
    path('noticia_create_form/', NoticiaCreate.as_view(), name='noticia_create_form'),
    path('noticia_create_long_form/', NoticiaCreateLongForm, name='noticia_create_long_form'),
    path('texto_create_long_form/', TextoCreateLongForm, name='texto_create_long_form'),
    path('imagem_create_long_form/', ImagemCreateLongForm, name='imagem_create_long_form'),
    path('video_create_long_form/', VideoCreateLongForm, name='video_create_long_form'),
    path('show_noticia_long_form/<int:pk>', ShowNoticiaLongForm, name='show_noticia_long_form'),
    path('noticia_update_form/<int:pk>', NoticiaUpdate.as_view(), name='noticia_update_form'),
    path('noticia_update_long_form/<int:pk>', NoticiaUpdateLongForm, name='noticia_update_long_form'),
    path('imagem_update_long_form/<int:pk>', ImagemUpdateLongForm, name='imagem_update_long_form'),
    path('video_update_long_form/<int:pk>', VideoUpdateLongForm, name='video_update_long_form'),
    path('texto_update_long_form/<int:pk>', TextoUpdateLongForm, name='texto_update_long_form'),
    path('noticia_confirm_delete/<int:pk>', NoticiaDelete.as_view(), name='noticia_confirm_delete'),
    path('whatsapp_account_list/', WhatsAppAccountView.as_view(), name='whatsapp_account_list'),
    path('whatsapp_account_create_form/', WhatsAppAccountCreate.as_view(), name='whatsapp_account_create_form'),
    path('whatsapp_account_update_form/<int:pk>', WhatsAppAccountUpdate.as_view(), name='whatsapp_account_update_form'),
    path('whatsapp_account_delete_confirmation/<int:pk>', WhatsAppAccountDelete.as_view(), name='whatsapp_account_delete_confirmation'),  
    
]

APP-Campus-Online-v6.0/campus_online/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('campus_app.urls')),
    path('', include('accounts.urls')),
    path('', include('pwa.urls')),
]

APP-Campus-Online-v6.0/campus_app/models.py
from django.db import models
from django.contrib.auth.models import User


def get_full_name(self):

    return self.first_name + ' ' + self.last_name


User.add_to_class("__str__", get_full_name)


class Noticia(models.Model):

    usuarios = models.ManyToManyField(User, related_name="usuario_noticia")
    titulo = models.CharField(max_length=200)
    palavras_chave = models.CharField(max_length=200, null=True, blank=True, default='')
    resumo = models.CharField(max_length=500, null=True, blank=True, default='')
    texto = models.TextField(max_length=600)
    prioridade = models.IntegerField(default=0)
    link_externo = models.CharField(max_length=300, null=True, blank=True, default='')
    link_foto = models.CharField(max_length=300, null=True, blank=True, default='')
    link_audio = models.CharField(max_length=300, null=True, blank=True, default='')
    link_video = models.CharField(max_length=300, null=True, blank=True, default='')
    autoria_midia = models.CharField(max_length=300, null=True, blank=True, default='')
    link_georreferenciamento = models.CharField(max_length=300, null=True, blank=True, default='')
    data_publicacao = models.DateTimeField(auto_now_add=True)
    dia_publicacao = models.DateField(auto_now_add=True)

class Imagem(models.Model):
    link_foto_long_form =models.CharField(max_length=300, null=True, blank=True, default='')
    autoria_midia_imagem = models.CharField(max_length=300, null=True, blank=True, default='')
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)

#criando nova tabela para armazenar vários vídeos referentes a uma mesma notícia
class Video(models.Model):
    link_video_long_form = models.CharField(max_length=300, null=True, blank=True, default='')
    autoria_midia_video = models.CharField(max_length=300, null=True, blank=True, default='')
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)

class TextoMateria(models.Model):
    subtitulo = models.CharField(max_length=200, null=True, blank=True, default='')
    texto_materia = models.TextField(max_length=2000)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)


class WhatsAppAccount(models.Model):

    cod = models.AutoField(primary_key=True, null=False)
    numero_telefone = models.CharField(max_length=20, null=False)

    def __str__(self):

        return self.numero_telefone

APP-Campus-Online-v6.0/campus_app/views.py
from django.urls import reverse_lazy
from .models import Imagem, Noticia, TextoMateria, Video, WhatsAppAccount
from django.contrib.auth.models import Group
from .forms import NoticiaForm, WhatsAppAccountCreateForm, TextoMateriaForm, VideoForm, ImagemForm
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.dates import DayArchiveView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
import datetime

def ShowNoticiaLongForm(request, pk):
    
    noticia = Noticia.objects.get(id = pk)
    imagem = Imagem.objects.get(noticia_id = pk)
    video = Video.objects.get(noticia_id = pk)
    texto_materia = TextoMateria.objects.get(noticia_id = pk)
    context = {
        'noticia': noticia,
        'imagem': imagem,
        'video': video,
        'texto_materia': texto_materia
    }
    return render(request, 'show_noticia_long_form.html', context)

class HomeView(TemplateView):

    template_name = "campus_app/home.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['noticias'] = Noticia.objects.order_by('-dia_publicacao', '-prioridade', '-data_publicacao')[:20]
        context['data'] = datetime.date.today()
        record = WhatsAppAccount.objects.order_by('-cod')[:1]
        number = None
        context['whatsapp'] = None

        if record:

            number = record[0]

            context['whatsapp'] = 'https://wa.me/' + str(number) + '?text=Ol%C3%A1,%20peguei%20esse%20n%C3%BAmero%20no%20App%20Campus%20Online'

        return context


class NoticiaDataView(DayArchiveView):

    template_name = "campus_app/noticia_archive_day.html"
    date_field = "dia_publicacao"
    queryset = Noticia.objects.order_by('-dia_publicacao', '-prioridade', '-data_publicacao')
    allow_future = True
    allow_empty = True

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        queryset = Noticia.objects.order_by('-dia_publicacao', '-prioridade', '-data_publicacao')
        context['noticias'] = queryset
        context['data'] = datetime.date(self.get_year(), self.get_month(), self.get_day())
        record = WhatsAppAccount.objects.order_by('-cod')[:1]
        number = None
        context['whatsapp'] = None

        if record:

            number = record[0]

            context['whatsapp'] = 'https://wa.me/' + str(number) + '?text=Ol%C3%A1,%20peguei%20esse%20n%C3%BAmero%20no%20App%20Campus%20Online'

        return context


class NoticiaView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):

    permission_required = 'campus_app.view_noticia'
    template_name = "campus_app/noticia_list.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['noticias'] = Noticia.objects.order_by('-data_publicacao').all
        context['perfil'] = Group.objects.filter(user = self.request.user)
        record = WhatsAppAccount.objects.order_by('-cod')[:1]
        number = None
        context['whatsapp'] = None

        if record:

            number = record[0]

            context['whatsapp'] = 'https://wa.me/' + str(number) + '?text=Ol%C3%A1,%20peguei%20esse%20n%C3%BAmero%20no%20App%20Campus%20Online'

        return context

      
class NoticiaCreate(LoginRequiredMixin, PermissionRequiredMixin, FormView):

    permission_required = 'campus_app.add_noticia'
    template_name = 'campus_app/noticia_form.html'
    form_class = NoticiaForm
    success_url = reverse_lazy('noticia_list')

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        record = WhatsAppAccount.objects.order_by('-cod')[:1]
        number = None
        context['whatsapp'] = None

        if record:

            number = record[0]

            context['whatsapp'] = 'https://wa.me/' + str(number) + '?text=Ol%C3%A1,%20peguei%20esse%20n%C3%BAmero%20no%20App%20Campus%20Online'

        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

@login_required
def NoticiaCreateLongForm(request):

    if request.method == 'POST':
        noticia_form = NoticiaForm(request.POST)

        if noticia_form.is_valid():
            noticia_form.save()
            return redirect('noticia_list')        

        else:
            context = {
                'noticia_form': noticia_form,
            }

    else:
        context = {
            'noticia_form': NoticiaForm(),
        }

    return render(request, 'campus_app/noticia_create_long_form.html', context)

@login_required
def TextoCreateLongForm(request):

    if request.method == 'POST':
        TextoMateria_form = TextoMateriaForm(request.POST)

        if TextoMateria_form.is_valid():
            TextoMateria_form.save()
            return redirect('noticia_list')        

        else:
            context = {
                'TextoMateria_form': TextoMateria_form
            }
            return render(request, 'campus_app/texto_create_long_form.html', context)
    else:
        context = {
            'TextoMateria_form': TextoMateriaForm()
        }
        return render(request, 'campus_app/texto_create_long_form.html', context)

@login_required
def ImagemCreateLongForm(request):
    
    if request.method == 'POST':
        imagem_form = ImagemForm(request.POST)

        if imagem_form.is_valid():
            imagem_form.save()
            return redirect('noticia_list')        

        else:
            context = {
                'imagem_form': imagem_form
            }
            return render(request, 'campus_app/imagem_create_long_form.html', context)
    else:
        context = {
            'imagem_form': ImagemForm()
        }
        return render(request, 'campus_app/imagem_create_long_form.html', context)

@login_required
def VideoCreateLongForm(request):
    
    if request.method == 'POST':
        video_form = VideoForm(request.POST)

        if video_form.is_valid():
            video_form.save()
            return redirect('noticia_list')        

        else:
            context = {
                'video_form': video_form
            }
            return render(request, 'campus_app/video_create_long_form.html', context)
    else:
        context = {
            'video_form': VideoForm()
        }
        return render(request, 'campus_app/video_create_long_form.html', context)


class NoticiaUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    permission_required = 'campus_app.change_noticia'
    model = Noticia
    form_class = NoticiaForm
    success_url = reverse_lazy('noticia_list')
    template_name = 'campus_app/noticia_update_form.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        record = WhatsAppAccount.objects.order_by('-cod')[:1]
        number = None
        context['whatsapp'] = None

        if record:

            number = record[0]

            context['whatsapp'] = 'https://wa.me/' + str(number) + '?text=Ol%C3%A1,%20peguei%20esse%20n%C3%BAmero%20no%20App%20Campus%20Online'

        return context

@login_required
def NoticiaUpdateLongForm(request, pk):
    
    noticia = get_object_or_404(Noticia, id = pk)

    noticia_form = NoticiaForm(instance=noticia)

    if(request.method == 'POST'):
        noticia_form = NoticiaForm(request.POST, instance=noticia)
        
        if(noticia_form.is_valid()):
            noticia = noticia_form.save(commit=False)
            noticia.titulo = noticia_form.cleaned_data['titulo']
            noticia.resumo = noticia_form.cleaned_data['texto']
            noticia.prioridade = noticia_form.cleaned_data['prioridade']
            noticia.link_foto = noticia_form.cleaned_data['link_foto']
            noticia.autoria_midia = noticia_form.cleaned_data['autoria_midia']
            noticia.link_video = noticia_form.cleaned_data['link_video']
            noticia.save()

            return redirect('noticia_list')
        else:
            context = {
                'noticia_form': noticia_form
            }
            return render(request, 'campus_app/noticia_update_long_form.html', context)
    elif(request.method == 'GET'):
        context = {
            'noticia_form': noticia_form
        }
        return render(request, 'campus_app/noticia_update_long_form.html', context)

@login_required
def ImagemUpdateLongForm(request, pk):
    imagem = get_object_or_404(Imagem, id = pk)
    imagem_form = ImagemForm(instance=imagem)
    if(request.method == 'POST'):
        imagem_form = ImagemForm(request.POST, instance=imagem)
        if(imagem_form.is_valid()):
            imagem = imagem_form.save(commit=False)
            imagem.link_foto_long_form = imagem_form.cleaned_data['link_foto_long_form']
            imagem.autoria_midia_imagem = imagem_form.cleaned_data['autoria_midia_imagem']
            imagem.save()
        else:
            context = {
                'imagem_form': imagem_form
            }
            return render(request, 'campus_app/imagem_update_long_form.html', context)
    elif(request.method == 'GET'):
        context = {
            'imagem_form': imagem_form
        }
        return render(request, 'campus_app/imagem_update_long_form.html', context)

@login_required
def VideoUpdateLongForm(request, pk):
    video = get_object_or_404(Video, id = pk)
    video_form = VideoForm(instance=video)
    if(request.method == 'POST'):
        video_form = VideoForm(request.POST, instance=video)
        if(video_form.is_valid()):
            video = video_form.save(commit=False)
            video.link_video_long_form = video_form.cleaned_data['link_video_long_form']

APP-Campus-Online-v6.0/campus_app/templates/campus_app/base.html
<!doctype html>
{% load static %}
{% load pwa %}
{% load sass_tags %}
{% load fontawesome_5 %}
<html lang="pt">
  <head>
    {% progressive_web_app_meta %}
    {% fontawesome_5_static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Plataforma de veiculação de notícias do Campus Online" />
    <title>Campus Multiplataforma</title>
    <link href="{% sass_src 'campus_app/styles.scss' %}" rel="stylesheet" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="theme-color" content="#536878">
    <script src="https://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="https://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:300,400,500,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'campus_app/imagens/favicon-novo.ico' %}" type="image/x-icon" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-154211701-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-154211701-1');
    </script>
  </head>
  <body>
    <div class="app">
      <sidenav id="mySidenav" class="sidenav">
        <span class="closebtn" onClick={closeNav()}><i class='material-icons'>chevron_left</i></span>
        <div class="content">
          {% if user.is_authenticated %}
            <p class="login-link" id="panel-link"><a href="{% url 'dashboard' %}" class="user-link">{% fa5_icon 'grip-horizontal' 'fas' %} Painel de Controle</a></p>
            <p class="login-link" id="logout-link"><a href="{% url 'logout' %}" class="user-link">{% fa5_icon 'sign-out-alt' 'fas' %} Sair</a></p>
          {% else %}
            <p class="login-link"><a href="{% url 'login' %}" class="user-link">{% fa5_icon 'sign-in-alt' 'fas' %} Entrar</a></p>
          {% endif %}
          <p>Plataformas do Campus Online</p>
          <ul>
            <li>
              <a href="http://campus.fac.unb.br/" target="_blank" onClick={closeNav()}>{% fa5_icon 'globe' 'fas' %} Site</a>
            </li>
            <li>
              <a href="https://twitter.com/campusitounb" class="twitter" target="_blank" onClick={closeNav()}>{% fa5_icon 'twitter' 'fab' %} Twitter</a>
            </li>
            <li>
              <a href="https://www.facebook.com/onlinecampus/" class="facebook" onClick={closeNav()} target="_blank">{% fa5_icon 'facebook-square' 'fab' %} Facebook</a>
            </li>
            <li>
              <a href="https://www.instagram.com/campusonline/" class="instagram" onClick={closeNav()} target="_blank">{% fa5_icon 'instagram' 'fab' %} Instagram</a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UChegNOjzApuGBTQyPo3I27Q" onClick={closeNav()} target="_blank">{% fa5_icon 'youtube' 'fab' %} Youtube</a>
            </li>
            {% if whatsapp != None %}
              <li>
                <a href="{{ whatsapp }}" onClick={closeNav()} target="_blank">{% fa5_icon 'whatsapp' 'fab' %} Whatsapp</a>
              </li>
            {% endif %}
          </ul>
          <p>Links da FAC</p>
          <ul>
            <li>
              <a href="http://fac.unb.br/" onClick={closeNav()} target="_blank">{% fa5_icon 'globe' 'fas' %} Site</a>
            </li>
            <li>
              <a href="https://twitter.com/fac_unb" onClick={closeNav()} target="_blank">{% fa5_icon 'twitter' 'fab' %} Twitter</a>
            </li>
            <li>
              <a href="https://www.facebook.com/faculdadedecomunicacao/" onClick={closeNav()} target="_blank">{% fa5_icon 'facebook-square' 'fab' %} Facebook</a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UChJBFMMGoVw2yXeFIllVnZw" onClick={closeNav()} target="_blank">{% fa5_icon 'youtube' 'fab' %} Youtube</a>
            </li>
            <li>
              <a href="https://issuu.com/campusunb" onClick={closeNav()} target="_blank">{% fa5_icon 'link' 'fas' %} Issuu</a>
            </li>
          </ul>
        </div>
      </sidenav>
      <header>
        <script>
          function openNav() {
              var sidenav = document.getElementById("mySidenav");
              sidenav.style.display = "block";
              sidenav.style.transform = "translateX(0px)";
              sidenav.classList.add("addShadow");
              //document.getElementById("opensidenav").style.visibility = "hidden";
          }
          function closeNav() {
              var sidenav = document.getElementById("mySidenav");
              sidenav.style.transform = "translateX(-70vw)";
              sidenav.style.display = "block";
              sidenav.classList.remove("addShadow");
              //document.getElementById("opensidenav").style.visibility = "visible";
          }
          $( document ).ready(function() {
            var today = new Date()
            $("#year").text(today.getFullYear())
          })
        </script>
      </header>
      <div class="app-header">
        <span id="opensidenav" onclick="openNav()">&#9776;</span>
        <a href="{% url 'home' %}"><img src="{% static 'campus_app/imagens/Logo-Campus1.png' %}" class="app-logo" alt="logo"></a>
      </div>
      <div class="app-content">
        {% block content %}{% endblock %}
      </div>
      <footer class="footer">
        <h4><span id="year">2019</span> FAC/CIC</h4>
      </footer>
      <script>
        $(document).ready(function () {
          var header = document.getElementsByClassName("app-header")[0]
          var logo = document.getElementsByClassName("app-logo")[0]
          $(document).scroll(function() {
            if ($(document).scrollTop() < 200) {
              header.id = ""
            } else if ($(document).scrollTop() >= 200) {
              header.id = "app-header-scrolled"
            }
          })
        })
      </script>
    </div>
  </body>
</html>

APP-Campus-Online-v6.0/campus_app/templates/campus_app/noticia_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="app">
      <div style="height: 100px;"></div>
        <center><h1>Remoção de Notícia</h1></center>
        <p> <a class="btn" href="{% url 'noticia_list' %}">Cancelar</a> </p>
        <form method="post">
          {% csrf_token %}
          <p><b>Você está certo de que quer excluir "{{ object.titulo }}" ?</b></p>
          <input class="btn" type="submit" value="Confirmar">
        </form>
      <div style="height: 100px;"></div>
    </div>
{% endblock %}

APP-Campus-Online-v6.0/campus_app/templates/campus_app/noticia_update_form.html
{% extends "base.html" %}
{% load fontawesome_5 %}

{% block content %}
    <div class="news-form">
        <p> <a class="back-link" href="{% url 'noticia_list' %}">{% fa5_icon 'chevron-left' 'fas' %} Voltar</a> </p>
        <form method="post">
          {% csrf_token %}
          <h3>Publicado por</h3>
          <span id="open-users" onclick="openUsers()">{% fa5_icon 'chevron-down' 'fas' %} Exibir usuários</span>
          <div id="users-container">
            {{ form.usuarios }}
          </div>
          <h3>Título</h3>
          <p>{{ form.titulo }}</p>
          <div class="error">{{ form.titulo.errors }}</div>
          <h3>Texto</h3>
          <p>{{ form.texto }}</p>
          <div class="error">{{ form.texto.errors }}</div>
          <h3>Prioridade</h3>
          <p>{{ form.prioridade }}</p>
          <div class="error">{{ form.prioridade.errors }}</div>
          <h3>Link externo</h3>
          <p>{{ form.link_externo }}</p>
          <div class="error">{{ form.link_externo.errors }}</div>
          <h3 class="link-tip">Link video</h3>
          <small>Vídeos não poderão ser exibidos na prévia, mas aparecerão normalmente na versão publicada.</small>
          <p>{{ form.link_video }}</p>
          <div class="error">{{ form.link_video.errors }}</div>
          <h3 class="link-tip">Link imagem</h3>
          <small>Caso a imagem não apareça na prévia, verifique se o link está correto.</small>
          <p>{{ form.link_foto }}</p>
          <div class="error">{{ form.link_foto.errors }}</div>
          <h3 class="link-tip">Autoria da imagem</h3>
          <small>Caso seja inserida imagem, utilize este campo para determinar a autoria.</small>
          <p>{{ form.autoria_midia }}</p>
          <div class="error">{{ form.autoria_midia.errors }}</div>
          <button class="link" type="submit">Publicar</button>
          <a class="link-outline" href="{% url 'noticia_confirm_delete' noticia.id %}">Remover</a>
        </form>
        <h3>Prévia da Notícia:</h3>
      </div>
    <div class="preview-news">
      <div class="newsList">
        <div class="dateDivider">08/10/2088</div>
        <div class="newsContent">
          <div id="preview-titulo" class="headline upper">Título</div>
          <div class="author"><b>Por Autor</b></div>
          <div class="adtInfo">
            <div class="timestamp">08/10/2088 09h28</div>
          </div>
          <div class="media">
            <div>
              <center><img class="newsImg" src="" alt="A imagem ou vídeo aparecerá aqui."></center>
              <center><figcaption id="preview-autoria"></figcaption></center>
            </div>    
          </div>
          <div class="texto">
            <p id="preview-texto">Texto</p>
          </div>
            <a class="link" id="preview-link" href="" target="_blank">Leia mais</a>
        </div>
      </div>
    </div>
    <div class="endPage"></div>

    <script>
      $( document ).ready(function() {
        var titulo_input = $("#id_titulo")
        var text_input = $("#id_texto")
        var link_input = $("#id_link_externo")
        var foto_input = $("#id_link_foto")
        var autoria_input = $("#id_autoria_midia")

        $("#preview-titulo").text(titulo_input.val())
        $("#preview-texto").text(text_input.val())
        $("#preview-link").attr("href", link_input.val())
        $(".newsImg").attr("src", foto_input.val())
        $("#preview-autoria").text(autoria_input.val())

        titulo_input.change(function() {
          $("#preview-titulo").text(titulo_input.val())
        });

        text_input.change(function() {
          $("#preview-texto").text(text_input.val())
        });

        link_input.change(function() {
          $("#preview-link").attr("href", link_input.val())
        });

        foto_input.change(function() {
          $(".newsImg").attr("src", foto_input.val())
        });

        autoria_input.change(function() {
          $("#preview-autoria").text(autoria_input.val())
        });

        var today = new Date()
        var time = new Date()

        today = String(today.getDate()).padStart(2, '0') + '/' + String(today.getMonth() + 1).padStart(2, '0') + '/' + today.getFullYear()
        $(".dateDivider").text(today)
        today += " " + ('0' + time.getHours()).slice(-2) + ":" + ('0' + time.getMinutes()).slice(-2)
        $(".timestamp").text(today)

      });

      function openUsers () {
        $("#users-container").slideToggle("slow")
        $("#open-users i").toggleClass("fa-chevron-down")
        $("#open-users i").toggleClass("fa-chevron-up")
      }
    </script>
{% endblock %}